<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WebShoppieAalst.Api.Contracts\WebShoppieAalst.Api.Contracts.csproj" />
      <ProjectReference Include="..\WebShoppieAalst.Domain.Services\WebShoppieAalst.Domain.Services.csproj" />
    </ItemGroup>

</Project>
